#!/bin/bash
#
# filter source list
# input: srclist and src_to_remove (generated by srclist_optimize.sh)
# output: srclist_new

export PATH="/c/Program Files (x86)/Atollic/TrueSTUDIO for STM32 9.3.0/ARMTools/bin:"$PATH 
export PATH="/c/Program Files (x86)/Atollic/TrueSTUDIO for STM32 9.3.0/PCTools/bin:"$PATH 
export PATH="/c/Program Files (x86)/Atollic/TrueSTUDIO for STM32 9.3.0/Tools:"$PATH 
export TOOLCHAIN_PREFIX=arm-atollic-eabi

cd ../..

cat 'srclist' | while read fn; do
	if ! grep "$(echo $fn | sed 's/\./\\\./')" src_to_remove >> /dev/null 2>&1; then
		echo $fn
	fi
done | tee 'srclist_new'

echo 'finished'

read x